application: ntuintrocsg03
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /db.*
  script: admindb.py

- url: /courses.*
  script: courses.py

- url: /resources.*
  script: resources.py

- url: /signup.*
  script: signup.py

- url: /upload.*
  script: upload.py

- url: /resources.*
  script: resource.py

- url: /.*
  script: taskbook.py


