application: ntuintrocsg03
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: /files/upload.html
  script: files.py
  login: required

- url: /files/upload
  script: files.py
  login: required

- url: /files/.*
  script: files.py

- url: /resource/.*
  script: resource.py

- url: /.*
<<<<<<< HEAD
  script: taskbook.py
=======
  script: taskbook.py
>>>>>>> master
