application: ntuintrocsg03
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /db.*
  script: admindb.py

- url: /test/.*
  script: upload.py

- url: /resource/.*
  script: resource.py
  
- url: /.*
  script: taskbook.py


