application: ntuintrocsg03
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:



- url: /stylesheets
  static_dir: stylesheets

- url: /signup.*
  script: signup.py

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: /you.*
  script: you.py

- url: /search.*
  script: search.py

- url: /files/upload.html
  script: files.py
  login: required

- url: /files/upload
  script: files.py
  login: required

- url: /files/.*
  script: files.py

- url: /resource/.*
  script: resource.py

- url: /.*
  script: taskbook.py

