application: ntuintrocsg03
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /test/.*
  script: upload.py
  
- url: /.*
  script: taskbook.py
  

