application: ntuintrocsg03
version: 2
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /test/.*
  script: test.py

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: /me
  static_dir: me
  
- url: /guestbook/.*
  script: guestbook.py
  
- url: /files/upload.html
  script: files.py
  login: required

- url: /files/upload
  script: files.py
  login: required

- url: /files/.*
  script: files.py

- url: /resource/.*
  script: resource.py

- url: /.*
  script: taskbook.py